version: '3'
services:
 mysql:
    image: bitnami/mysql:5.7
    container_name: mysql-posty
    restart: always
    environment:
      - COMPANY=wd
      - MYSQL_DATABASE=posty
      - MYSQL_ROOT_PASSWORD=somepass
      - MYSQL_USER=admin
      - MYSQL_ROOT_HOST='%'
      - MYSQL_PASSWORD=somepass
    ports:
      - "43314:3306"
    volumes:
      - "./data:/bitnami/mysql/data"
      - "./mysql_my.cnf:/opt/bitnami/mysql/conf/bitnami/my_custom.cnf"
